# SolarSINDy dataset artifact
# Data files for storm monitoring and discovery demonstration

[[SolarSINDyData]]
arch = "*"
git-tree-sha1 = "09bd6558f3ba3bfea4a6dfabed2aee2f80e02892"
os = "*"

[SolarSINDyData.download]
sha256 = "3e235a42cb762feaff86cf4026f1c2bc126"
url = "https://github.com/jake-w-liu/SolarSINDy.jl/releases/download/v0.1.0/data.tar.gz"

