# SolarSINDy dataset artifact
# Data files for storm monitoring and discovery demonstration

[[SolarSINDyData]]
arch = "*"
git-tree-sha1 = "b7f8dee6463a3328b753c50134aa10529b41dfdb"
os = "*"

[SolarSINDyData.download]
sha256 = "3e235a42cb762feaff86cf4026f1c2bc126"
url = "https://github.com/jake-w-liu/SolarSINDy.jl/releases/download/v0.1.0/data.tar.gz"

